### ISSUE TITLE
ZOutputStream hangs at input stream end

### ISSUE THREAD

**Issue by uholeschak** [philippelatulippe/ZLIB.NET#2]
In ZOutputStream if the input stream is longer than the compressed stream content, Write() and finish() will hang.
In both functions an abort is required at stream end:
```csharp
    if (err == zlibConst.Z_STREAM_END)
    {
        break;
    }
}
while (z.avail_in > 0 || z.avail_out == 0);
```

**Comment by AraHaan** [comment]
Mind trying this in my fork? Also if you would like you can pull request it to my fork, and to Els_kom_new as it uses a modified Zlib.net from that fork.

**Comment by uholeschak** [comment]
The modification is not so complicated, I have added a patch file:
[ZOutputStream.cs.patch.zip](https://github.com/philippelatulippe/ZLIB.NET/files/2093631/ZOutputStream.cs.patch.zip)

**Comment by AraHaan** [comment]
Thanks, I will test this patch and apply it to my fork. After done you can clone it.

**Comment by AraHaan** [comment]
That should just work.

**Comment by CatGirlsAreLife** [comment]
@uholeschak want to test the new changes to our fork's master branch that adds some more fixes?

**Comment by uholeschak** [comment]
Sorry, at the moment I am using only the NuGet package (with derived classes), changing to source is a bit more difficult.

**Comment by CatGirlsAreLife** [comment]
I do plan to do a v1.04 release to nuget if I could find the motivation to set up appveyor to do it for me. :thinking:

**Comment by AraHaan** [comment]
I think more like a v1.0.3. @uholeschak But I am not sure if I can republish the update to nuget?

**Comment by uholeschak** [comment]
Simply try, I will see then if it's working as expected ...

**Comment by AraHaan** [comment]
It seems that according to a Microsoft employee, I will have to rename the project and republish unless the owner of the nuget moves the ownership to me to update it. Also note that because I made some changes using stylecop that there might be some breaking changes due to me uppercasing some fields and exposing ``z`` as ``Z`` in ``ZInputStream`` and ``ZOutputStream`` for getting the ``adler32`` value (or crc32 but faster) of the data.
And to do that it is ``[your stream].Z.Adler``. So be careful. Also ``finalize`` was renamed to ``Finalize``.

It also targets the latest C# language version and uses auto properties for some things that was fields too.

**Comment by AraHaan** [comment]
https://www.nuget.org/packages/zlib.managed/ @uholeschak

**Comment by uholeschak** [comment]
I tried to replace zlib, but I get the error message when I install your version:
Das Paket "zlib.managed 1.0.0" konnte nicht installiert werden. Sie versuchen, dieses Paket in ein Projekt zu installieren, das sich auf ".NETFramework,Version=v4.6.1" bezieht, das Paket enthält aber keine Assemblyverweise oder Inhaltsdateien, die mit diesem Framework kompatibel sind. Wenden Sie sich an den Paketersteller, um weitere Informationen zu erhalten.

**Comment by AraHaan** [comment]
oh yea, I target the latest version of .NET Framework 4.7.2.

**Comment by uholeschak** [comment]
Is this really required? If 4.0 is working it's best, then it could be used in more projects ...

**Comment by AraHaan** [comment]
Ye, that is true. I could change that.

**Comment by CatGirlsAreLife** [comment]
ok @uholeschak it has been changed.

**Comment by uholeschak** [comment]
Thanks, I have tested it now with the new version, seems to work without any problems.
