### ISSUE TITLE
z.deflate 失败

### ISSUE THREAD

**Issue by Nonastar** [philippelatulippe/ZLIB.NET#3]
我要压缩一些string类型的数据，大概400kb
`public override void  Write(System.Byte[] b1, int off, int len)
		{
			if (len == 0)
				return ;
			int err;
			byte[] b = new byte[b1.Length];
			System.Array.Copy(b1, 0, b, 0, b1.Length); 
			z.next_in = b;
			z.next_in_index = off;
			z.avail_in = len;
			do 
			{
				z.next_out = buf;
				z.next_out_index = 0;
				z.avail_out = bufsize;
				if (compress)
					err = z.deflate(flush_Renamed_Field);
				else
					err = z.inflate(flush_Renamed_Field);
				if (err != zlibConst.Z_OK && err != zlibConst.Z_STREAM_END) 
					throw new ZStreamException((compress?"de":"in") + "flating: " + z.msg);
				out_Renamed.Write(buf, 0, bufsize - z.avail_out);
			}
			while (z.avail_in > 0 || z.avail_out == 0);
		}`

err 返回 0
但是 z.avail_out 仍然还是4096

**Comment by AraHaan** [comment]
Take a look at my fork known and published on nuget as zlib.managed. Sadly however I am about to compare my fork to this one however as somehow a big snuck in that makes it decompress to all bytes to null on the correct decompressed length.

oh and btw it is also here: https://github.com/Elskom/zlib.managed/
